# Generated by Django 4.2.1 on 2023-05-24 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orden",
            fields=[
                ("idOrden", models.AutoField(primary_key=True, serialize=False)),
                ("idMascota", models.IntegerField()),
                ("cedulaDueno", models.CharField(max_length=20)),
                ("cedulaVeterinarioOrdena", models.CharField(max_length=20)),
                ("nombreMedicamento", models.CharField(max_length=100)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("anulacion", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("cedula", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=11)),
                ("usuario", models.CharField(max_length=10, null=True)),
                ("contraseña", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dueño", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                ("especie", models.CharField(max_length=100)),
                ("raza", models.CharField(max_length=100)),
                ("tamano", models.CharField(max_length=100)),
                ("peso", models.FloatField()),
                (
                    "cedula",
                    models.ForeignKey(
                        db_column="cedula_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinaria.persona",
                    ),
                ),
            ],
        ),
    ]
