# Generated by Django 4.2.1 on 2023-05-27 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="cedulaDueno",
            field=models.ForeignKey(
                db_column="cedulaDueno",
                on_delete=django.db.models.deletion.CASCADE,
                to="veterinaria.persona",
            ),
        ),
        migrations.AlterField(
            model_name="orden",
            name="idMascota",
            field=models.ForeignKey(
                db_column="idMascota",
                on_delete=django.db.models.deletion.CASCADE,
                to="veterinaria.mascota",
            ),
        ),
        migrations.CreateModel(
            name="factura",
            fields=[
                ("idFactura", models.AutoField(primary_key=True, serialize=False)),
                ("idMascota", models.IntegerField(null=True)),
                ("cedulaDueno", models.IntegerField(max_length=100)),
                ("producto", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                ("valor", models.FloatField(max_length=100)),
                ("fecha_fact", models.DateField(default=django.utils.timezone.now)),
                (
                    "idorden",
                    models.ForeignKey(
                        db_column="idOrden",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veterinaria.orden",
                    ),
                ),
            ],
        ),
    ]
