# Generated by Django 4.2.1 on 2023-05-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0002_alter_orden_ceduladueno_alter_orden_idmascota_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mascota",
            old_name="id",
            new_name="idMascota",
        ),
    ]
