# Generated by Django 4.2.1 on 2023-05-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinaria", "0003_rename_id_mascota_idmascota"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mascota",
            old_name="idMascota",
            new_name="id",
        ),
    ]
